config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'
  get 'sessions/destroy'
  get 'sessions/failure'
  get 'sessions/new', to: 'sessions#new', as: 'login'
  resources :diaries, only: [:new, :create, :show]
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'
  delete '/logout', to: 'sessions#destroy'
  post '/auth/twitter2', to: 'sessions#auth_twitter2', as: 'auth_twitter2'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/diary.rb
class Diary < ApplicationRecord
    belongs_to :user, optional: true
    validates :content, presence: { message: "1文字以上入力してください" }, length: { maximum: 200, message: "200文字以下で入力してください" }

   # scope :created_today, ->(user) { where(user: user, created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :diaries
  def self.find_or_create_from_auth(auth)
    user = find_or_create_by(uid: auth['uid'], provider: auth['provider'])
    user.update(
      name: auth['info']['name'],
      image: auth['info']['image'],
      provider: auth['provider']
    )
    user
  end
end

app/controllers/admin/migrations_controller.rb
class Admin::MigrationsController < ApplicationController
    def index
        if Rails.env.production?
          ActiveRecord::Base.connection.migration_context.migrate
          render plain: "Migrations ran successfully"
        else
          render plain: "This action is only allowed in production"
        end
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #  helper_method :current_user, :user_signed_in?, :owner?

  #private

end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  #before_action :authenticate_user!
  before_action :set_diary, only: [:show, :edit, :update, :destroy]
  #before_action :authorize_owner!, only: [:show, :edit, :update, :destroy]

  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.new(diary_params)
    @diary.user_name = '名無し' if @diary.user_name.blank?

    if @diary.save
      prompt = "#{@diary.user_name}が主人公、#{@diary.content}を#{@diary.style}にして、50字以上120文字以内で出力してください。"
      openai_service = OpenaiService.new

      begin
        generated_content = openai_service.generate_indirect_message(prompt)
        Rails.logger.info "Generated content: #{generated_content}"
        @diary.update(generated_content: generated_content)
        redirect_to @diary
      rescue => e
        Rails.logger.error "Failed to generate content: #{e.message}"
        flash[:alert] = "Failed to generate content: #{e.message}"
        render :new
      end
    else
      flash[:alert] = "Failed to save diary."
      render :new
    end
  end

  def show
  end

  private

  def set_diary
    @diary = Diary.find(params[:id])
  end

  def diary_params
    params.require(:diary).permit(:user_name, :content, :style)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #skip_before_action :verify_authenticity_token, only: [:auth_twitter2, :create]
  def new
    Rails.logger.debug "Session: #{session.to_hash}"
  end


  def create
    @diary = Diary.new(diary_params)
    @diary.user_name = '名無し' if @diary.user_name.blank?

    if @diary.save
      prompt = "#{@diary.user_name}が主人公、#{@diary.content}を#{@diary.style}にして、80字以上120文字以内で出力してください。"
      openai_service = OpenaiService.new

      begin
        generated_content = openai_service.generate_indirect_message(prompt)
        Rails.logger.info "Generated content: #{generated_content}"
        @diary.update(generated_content: generated_content)
        redirect_to @diary, notice: 'Diary was successfully created.'
      rescue => e
        Rails.logger.error "Failed to generate content: #{e.message}"
        flash[:alert] = "Failed to generate content: #{e.message}"
        render :new
      end
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, status: :see_other
  end

  def failure
    redirect_to root_path, alert: 'ログインに失敗しました'
  end
end

app/helpers/admin/migrations_helper.rb
module Admin::MigrationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def default_meta_tags
        {
          site: 'Post代行',
          title: '〜面倒くさがりの君へ〜',
          reverse: true,
          charset: 'utf-8',
          description: 'Chat-GPTがあなたの代わりにXのPostを考えてくれます',
          keywords: 'X,Chat-GPT,ポスト',
          canonical: request.original_url,
          separator: '|',
          og: {
            site_name: :site,
            title: :title,
            description: :description,
            type: 'website',
            url: request.original_url,
            image: image_url('Post.png'), # 配置するパスやファイル名によって変更すること
            local: 'ja-JP'
          },
          # Twitter用の設定を個別で設定する
          twitter: {
            card: 'summary_large_image', # Twitterで表示する場合は大きいカードにする
            site: '@omaty410', # アプリの公式Twitterアカウントがあれば、アカウント名を書く
            image: image_url('Post.png') # 配置するパスやファイル名によって変更すること
          }
        }
      end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/diaries/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/diaries/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Post代行</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
    <div class="title-image-container " %>
    <%= image_tag 'title.png', alt: 'Post代行' %>
    </div>

  <%= form_with model: @diary, local: true , html: { data: { turbo: false }, class: 'centered-form' } do |form| %>
    <% if @diary.errors.any? %>
      <div id="error_explanation">
      <h2><%= pluralize(@diary.errors.count, "error") %>が発生しました:</h2>

        <ul>
          <% @diary.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :user_name, "ユーザー名" %>
      <%= form.text_field :user_name, size: 20 %>
    </div>

    <div class="field">
      <%= form.label :content, "内容" %>
      <%= form.text_area :content, placeholder: '今日の出来事や気分を教えてね
    （1文字以上、200文字以内）', maxlength: 200 %>
    </div>

    <div class="field">
      <%= form.label :style, "スタイル" %>
      <%= form.select :style, options_for_select(['ギャル風','おじさん構文', '古風なスタイル', 'ビジネス風', 'ライトノベル風', '関西弁', '沖縄弁', 'メイドカフェの店員風', 'SF風', 'ホラー風', 'ファンタジー風', 'ポエム風', 'ドラマティック風','ツンデレ風','ぶりっ子風','キザ風'], selected: 'ギャル風'), { size: 10 }%>
    </div>

    <div class="actions">
      <%= form.submit '作成' %>
    </div>
  <% end %>

  <!-- 画像表示 -->
  <div class="image-container">
    <%= image_tag 'lazyham.png', alt: 'Lazy golden hamster', style: 'width:40%; height:auto;' %>
  </div>
</div>
</body>
</html>

app/views/diaries/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Postを考えたよ!</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <style>
    .highlighted-content {
      font-size: 1.0em;
      font-weight: bold;
      margin-top: 10px;
      margin-bottom: 10px;
      max-width: 50%;
      margin-left: auto;
      margin-right: auto;
      background-color: white; /* 背景色を白に設定 */
      padding: 10px; /* 余白を追加 */
      border-radius: 5px; /* 角を丸くする */
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* 影を追加 */
    }
    .image-container {
      margin-bottom: 20px;
    }
  </style>
</head>

<body>
<div class="container">
<div class="centered-text">
  <h1>Postを考えたよ!</h1>

  <p><strong>ユーザー名</strong></p>
  <div class="highlighted-content" style="font-size: 1.0em; font-weight: bold; margin-top: 20px; margin-bottom: 20px; max-width: 50%; margin-left: auto; margin-right: auto;">
  <p><%= @diary.user_name %></p>
  </div>

  <p><strong>スタイル</strong></p>
  <div class="highlighted-content" style="font-size: 1.0em; font-weight: bold; margin-top: 20px; margin-bottom: 20px; max-width: 50%; margin-left: auto; margin-right: auto;">
  <p><%= @diary.style %></p>
  </div>

  <!-- 目立たせるための内容 -->
    <p><strong>内容</strong></p>
    <div class="highlighted-content" style="font-size: 1.0em; font-weight: bold; margin-top: 20px; margin-bottom: 20px; max-width: 50%; margin-left: auto; margin-right: auto;">
    <p><%= @diary.generated_content %></p>
  </div>

  <!-- Twitterシェアボタン -->
  <a href="https://twitter.com/intent/tweet?text=<%= @diary.generated_content.truncate(120) %>%20#Post代行&url=https://chatgpt-messenger-2.onrender.com/" target="_blank" class="twitter-share-button">post</a>

  <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

  <!-- 新たなpostを作成リンクを一行下げる -->
  <div style="margin-top: 40px;">
    <%= link_to '新規作成', new_diary_path, class: 'btn btn-new-post'  %>
  </div>

  <!-- 画像表示 -->
  <div class="image-container" style="text-align:center; margin-top:20px;">
    <%= image_tag 'thinking.png', alt: 'Thinking Hamster', style: 'width:30%; height:auto;' %>
  </div>
</div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= display_meta_tags(default_meta_tags) %>

    <!-- OGP メタタグ -->
    <meta property="og:title" content="Your Page Title">
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:image" content="<%= image_url('Post.png') %>">
    <meta property="og:description" content="Description of your page">


    <link rel="icon" href="<%= asset_path 'favicon.ico' %>">


    <style>
      html, body {
        height: 100%;
        margin: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
      }
      .centered-text {
        text-align: center;
        margin-top: 20px;
      }
      .btn {
        display: inline-block;
        padding: 10px 20px;
        margin: 5px;
        font-size: 16px;
        font-weight: bold;
        text-align: center;
        text-decoration: none;
        border-radius: 25px;
        transition: background-color 0.3s, color 0.3s;
        border: none;
        cursor: pointer;
      }
      .btn-login {
        background-color: #1DA1F2;
        color: white;
      }
      .btn-login:hover {
        background-color: white;
        color: #1DA1F2;
        border: 2px solid #1DA1F2;
      }
      .btn-logout {
        background-color: #E0245E;
        color: white;
      }
      .btn-logout:hover {
        background-color: white;
        color: #E0245E;
        border: 2px solid #E0245E;
      }
      .container {
        text-align: center;
      }
    </style>
    <meta name="google-site-verification" content="4DKAeSiRdqisiDsRci4Y8ffsIFuCemQGKqOYl1MCd5k" />
  </head>

  <body>
  <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
    <div class="centered-text">
    
    </div>
  </body>
</html>